### ISSUE TITLE
Creation of the User

### ISSUE THREAD

**Issue by lfquissa** [EngenheirosDoHavaii/EngDSoft#11]
Description:
As a user, i would like to have the option to log in to the platform using my Gmail account. This would provide a more convenient login process.

Acceptance criteria: 
We need a functional interface of login, and integrate with Firebase. 

- [x] #24
- [x] #43
- [x] #59
- [x] #25

**Comment by AriadneBigheti** [comment]
Pipelines da execução dos testes dos PRs:
https://github.com/EngenheirosDoHavaii/EngDSoft/actions/runs/5428585554
https://github.com/EngenheirosDoHavaii/EngDSoft/actions/runs/5428660709
